import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Title from "./components/panes/title"
import "@/styles/globals.css";
import ConnectedPage from "./components/ConnectWrapper";
import Component from './index';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'spCoin',
  description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    }: {
        children: React.ReactNode
    }) {
    return (
        <>
            {/* <Title address={undefined} isConnected={undefined} connect={undefined} headerType={''} /> */}
            {/* <ConnectedPage Component={Component} /> */}
            {/* <ConnectedPage Component={children} /> */}
            {children}
        </>
    )
}
